# {{projectName}}

This project was generated by Project Base Generator. The canonical application rules are in `architecture/`; that directory is a versioned copy and does not require a link to the generator repository.

## Development

```bash
npm run dev
```

## Validation

```bash
npm run lint
npm run format:check
npm run typecheck
npm test
npm run build
```

The project uses npm and targets Node.js 22 LTS or newer. Optional integrations and framework-specific behavior are described in `architecture/`.
